### ISSUE TITLE
question in MEGAHIT

### ISSUE THREAD

**Issue by mant-ux** [RasmussenLab/vamb#107]
Hello, I use vamb to run correctly on the results of all spades assembly, but there are always errors in the results of megahit. The name of contings does not match the comparison of BAM hash. What is the reason? I have tried both minimap and BWA comparison tools, but t
he contings spliced by megahit still can't run. Thank you!

![image](https://user-images.githubusercontent.com/82646017/162401568-b0a292fd-f296-4a4a-85aa-974a6b221fa5.png)

**Comment by jakobnissen** [comment]
Dear @mant-ux 

First, which version of Vamb are you running? Secondly, can you verify by looking at the FASTA file and the BAM files that they are actually identical?
You can get the headers from the BAM file by running `samtools view -H myfile.bam | grep @SQ | cut -b 8- | cut -f 1`, and the headers of the FASTA file by running ` grep -oE '^>\S+' fasta.fna | cut -b 2-`. Then compare.

**Comment by jakobnissen** [comment]
It is possible this fails because BAM files by default truncate the header at the first whitespace, whereas Vamb does not.
I will fix this by making Vamb also truncate the header in the same way. Until then, you can solve it by renaming your FASTA files to only its identifier, or by disabling the refhash check.
