### ISSUE TITLE
parsing bam files does not scale well

### ISSUE THREAD

**Issue by nick-youngblut** [RasmussenLab/vamb#15]
It appears that parsing bam files is much slower than the equivalent steps for metabat2, especially if a contig size cutoff is applied (eg., min contig length of 2000). The difference is probably close to 10X, at least with larger bam files. It would be helpful if bam parsing by vamb could be sped up, so it can scale better. I'm finding the bam parsing step to be the limiting factor with applying vamb to large datasets.

**Comment by jakobnissen** [comment]
Dear @nick-youngblut 

This is definitely something I'd like to optimize. However, I'm not certain it's possible, and there's a few things I need to know before I can do any work on this.

In my own experience, Vamb parses BAM files several times faster than METABAT2's `jgi_summarize_bam_contig_depths` program. After just testing Vamb, it parses somewhere between 80k to 270k alignment records per second on my laptop, meaning it takes 11 minutes for my 5 GB BAM file. The speed seems to be mainly limited by the amount of extra alignments marked with XA - parsing these can take up the majority of the time if each alignment has multiple XA-marked extra alignments.

I can't do much to improve the speed of pysam, which Vamb relies on to parse the BAM files. But I can perhaps implement parsing the XA tags in Cython, although this will make it less portable, so I'm not sure it's worth it.

So, let me know:
1) What size are we talking about when you talk about large BAM files? 100 GB? Even larger? Approximately how many records do a typical of your BAM files take?
2) Does your speed with Vamb roughly match 80k alignment records per second per core?
3) Using `samtools view` and looking at your files, do each alignment have many extra alignment tagges `XA`? Approximately how many per record?

Alternatively, Vamb works quite well using the output from METABAT2's `jgi_summarize_bam_contig_depths`. Simply cut out the columns representing depth and convert it to a Numpy array. I've recently pushed an update to Vamb which allows it to read the RPKM directly from the output of `jgi_summarize_bam_contig_depths` rather than parsing the BAM files itself.

**Comment by jakobnissen** [comment]
There's a few things about your experience that struck me as odd:
First, Vamb should scale linearly with the number of alignment records, so it shouldn't be particularly bad for larger as opposed to smaller BAM files. It does also scale with the frequency of XA-tagged alignments and the number of extra alignments in the XA-tags, so perhaps larger BAM files also have more crossmapping (assuming you use BWA, which creates these XA tags)?
Second, the speed should not be affected by the minimum contig length. Have you directly experienced that the performance has dropped after setting `minsize` to 2000?
Perhaps there is something important I have overlooked.

**Comment by nick-youngblut** [comment]
I'm trying to run vamb on a pretty large dataset of ~400 bam files (each a few Gb). `jgi_summarize_bam_contig_depths` took ~1 day to process all of these bam files, while `vamb` has been working on these for over a week. Also, I tried raising the min contig length from 2000 to 4000, and that didn't seem to speed up the processing of the bam files. I used bowtie2 to generate the bam files. I'm running vamb commit d140880cdd218ce5e49f5b8a807a1f087d97dedb.

**Comment by jakobnissen** [comment]
Dear @nick-youngblut 

I've now looked more into it:

If you're using Bowtie2, the slowness in parsing the XA tags cannot be the problem here, so I will not spend time optimizing that. That leaves all the computation spent in pysam, iterating over the BAM file. That leaves really no room for optimization in Vamb - however, pysam uses htslib, and is pretty fast.

On my computer, parsing a BAM file with few XA tags using Vamb takes about 1.5 times as long as doing `samtools view my_bamfile.bam > /dev/null`. On our cluster with older CPUs the speed of Vamb when there are few XA tags works out to about 20k reads per second per core, and about 150k reads/(sec*core) on my laptop. Assuming you have CPUs similar to our cluster, you use 8 cores, and each of your 400 BAM files contain 50 million reads, it should take about 1.5 days to parse them all. Conversely, on a newer CPU using 32 cores, it should take a couple of hours.

Yet, it takes you more than a week. And since your jgi_summarize_bam_contig_depths takes one day, it can't be your computer that's slow. So, something else must be happening. It's not easy to know from my point of view.

One guess is that one of the subprocesses stalls or encounters an error. In earlier (non-`dev`) versions of Vamb, errors didn't propagate to the parent process properly, and while the error would be printed to sys.stderr, it would not exit properly. If that happened, there should be an error message. And, if that was the case, then the problem has already been fixed on `dev` and will be merged into `master` soon-ish.

On a side note, the commit you listed above does not appear to one from this Github repo. Are you sure you copied the right commit ID?

I'll leave this issue open since I can't properly resolve it at this moment.

**Comment by nick-youngblut** [comment]
Thanks @jakobnissen for really trying to troubleshoot this. 

Yeah, none of the bam files should include any XA tags, given that I used bowtie2.

I've been using 24 cores for the vamb job. 

There were no *.npz files (or any other files) in the temp output directory. 

I was using a pre-Jan 24 version of vamb. I've now updated and am re-running the large job. Maybe that will help.

**Comment by jakobnissen** [comment]
Closing this because the way to solve this is by solving #42.
