### ISSUE TITLE
hash of the whole fasta headers instead of just the ids

### ISSUE THREAD

**Issue by danpal96** [RasmussenLab/vamb#161]
vamb=4.0.1

When I use vamb with my contigs without renaming them I get the next error:

```
ValueError: At least one BAM file reference name hash to b8126ea6ff9bedc4ebb495695cd25129, expected c110292443b13cdc4d101e2114c17656. Make sure all BAM and FASTA headers are identical and in the same order.
```

This happens because in the `parsecontigs.py` `Composition.from_file` method the line `contignames.append(entry.header)` uses the whole header as the contig name (e.g. "contig1 description") istead of just the ID (e.g. "contig1"). I have resolved this by replacing this line with `contignames.append(entry.header.split()[0])`

**Comment by jakobnissen** [comment]
Dear @danpal96 

Thanks for the bug report. The fix is indeed to hash just the identifier when constructing the `Composition`.
Why not hash the entire header? Because SAM/BAM files only contain the identifier, not the header. Hence, if we want to check that the BAM files match the FASTA file, we cannot use the description.

Fixed by #162
