### ISSUE TITLE
Additional output file?

### ISSUE THREAD

**Issue by sjaenick** [RasmussenLab/vamb#165]
Hi,

currently, Vamb creates a clusters.tsv output file containing cluster to sequence mappings; downstream
tools like DAS_Tool (https://github.com/cmks/DAS_Tool) require a TSV file with the opposite direction, 
i.e. contig names in the first column and bin names in the second.

While the conversion is trivial, it would be nice to create this as an additional output directly within Vamb.

**Comment by jakobnissen** [comment]
Dear @sjaenick 

Since it's easy to do the conversion yourself `paste <(cut -f2 vae_clusters.tsv) <(cut -f1 vae_clusters.tsv) | head`, I don't think it's worth adding another input file.
I'm not too happy with Vamb's current output format. For example, it has the extension `.tsv` but is not a TSV file. However, if this is to be changed, I'd prefer
* To wait to change it until we release a breaking version of Vamb, and
* Change it to a well-known format, e.g. TSV
