### ISSUE TITLE
Vamb 4.1.3 has a header problem for loading fasta files 

### ISSUE THREAD

**Issue by Andyargueasae** [RasmussenLab/vamb#188]
Hi,

So I was using vamb 4.1.3 to bin the assembly: pure_plastid_contigs_without_highcov_contigs.fasta, with the type of headers and sequences:
">NODE_2018_length_2739_cov_8.344635
ACGT..."
">NODE_2191_length_2523_cov_6.987844
ACGT..."
">NODE_2540_length_2149_cov_8.234479
ACGT..."
">NODE_2621_length_2081_cov_21.597730
..."
">NODE_2693_length_2029_cov_4.394124
..."

But, there is an error coming constantly saying that the header doesn't match the regex pattern of SAM specification: 
<img width="802" alt="image" src="https://github.com/RasmussenLab/vamb/assets/88032525/32c8eb05-747b-47d9-82a2-c0259dd16ce6">

But it looks normal to me that my fasta headers are in regular style, may be something wrong with the regex compilation.

**Comment by jakobnissen** [comment]
Thank you for the report. This is a bug in Vamb that makes it fail when the newline is `\r\n` instead of `\n`. Windows typically uses `\r\n`, whereas Unix machines use `\n` to encode newlines.
You can fix this for now by deleting all the `\r` characters in the file by doing `tr -d '\r' infile > outfile` on the command line, but I will make a PR to fix the issue in Vamb shortly, such that the next released version will have this bug fixed.
