### ISSUE TITLE
AVAMB output for phamb

### ISSUE THREAD

**Issue by bhimbbiswa** [RasmussenLab/vamb#192]
Thank you for upgrading the VAMB tool.

I am keen on using phamb for viral binning. I am curious whether AAMB (z+y) can enhance vMAGs as well. As CheckM2 performs well with prokaryotes, I am unsure if AAMB clustering will positively impact my viral contigs.

Before diving into VAMB, I wanted to inquire whether AVAMB can lead to improved viral bins

Thanks and regards,

Bhim

**Comment by simonrasmu** [comment]
Hi Bhim,

We have not tested the impact of AAMB on vMAGs. However, you could use the output from either VAMB or AAMB as input to PHAMB. Whether the combined set of contigs from AVAMB (the full pipeline of AAMB+VAMB combined) will improve I am not sure. Any thoughts  @Paupiera ?

Best,

Simon

**Comment by bhimbbiswa** [comment]
Dear Simon,

Thank you very much for your kind reply.

I was assuming that with better bacterial MAGs, there will be fewer sequences left to contaminate vMAGs.

I am right now using AVAMB and will test both outputs (vae_clusters.tsv, Final_clusters.tsv) separately in phamb.

Regards,

Bhim

**Comment by Paupiera** [comment]
Dear Bhim,

Thanks for using AVAMB. During AVAMB's workflow bins are filtered with CheckM2, so I don't know how well it will perform to reconstruct viruses, since they might just be filtered out in this step. An alternative could be to use CheckV instead of CheckM2 to filter the bins, or even combine them somehow. However, since CheckV and CheckM2 produce output files with different outputs and output formats, replacing/combining CheckM2 with CheckV is not straightforward. 

Best regards,
Pau

**Comment by bhimbbiswa** [comment]
Dear Pau,

Thank you. I am using VAMB for now.

Regards,

Bhim
