### ISSUE TITLE
Qeuestion why not allow multi-mapping? 

### ISSUE THREAD

**Issue by SilasK** [RasmussenLab/vamb#193]
https://github.com/RasmussenLab/vamb/blob/311f22b4deead7ed50b80e6a8117d2d7f177b0a9/workflow_avamb/avamb.snake.conda.smk#L188C13-L188C34

In your workflow, you filter out secondary alignments. I don't understand why?

Multi-mapping is expected as we combine contigs from many samples. 
Isn't this a waste of resources to map a read multiple times and then remove all but one alignment?
Isn't the co-abundance pattern more correct if one allows multi-mapping (with some id threshold)?

**Comment by jakobnissen** [comment]
Dear @SilasK 

We filter out supplementary (flag 0x800), not secondary (flag 0x100) alignments.
The definition of supplmentary vs. secondary alignments are vague, but the SAM specification suggests supplementary alignments are for chimeric alignments (which we do not care about).

More broadly, we spent a lot of time thinking about how to deal with multimapping reads (see for example https://github.com/wwood/CoverM/issues/164), and the implementation in `vamb/parsebam.py` in Vamb 3.0. It's hard to figure out what correct behaviour really is here: Consider: For a contig assembled in sample A, what is its true abundance in sample B? Zero? Or nonzero? Our analysis suggests that, when using either bwa mem or minimap2, taking supplementary alignments into account doesn't improve overall abundance estimates and it certainly doesn't seem to improve binning.

In Vamb 4, this is a moot point, since we use `pycoverm` to get our abundance estimates, and this program simply ignores all secondary alignments anyway.
