### ISSUE TITLE
[Question] Why Vamb doesn't use canonical k-mers?

### ISSUE THREAD

**Issue by apcamargo** [RasmussenLab/vamb#21]
Hi @jakobnissen 

From what I've seen in Vamb's code it doesn't use canonical k-mers and I was wondering what is the reason for this choice. I'd expect that canonical k-mers would reduce memory usage and reduce overfitting in the neural network.

Is there something I'm missing out?

**Comment by jakobnissen** [comment]
Dear @apcamargo

Vamb does indeed use canonical kmers. It uses tetranucleotides (4-mers), yet the TNF matrix is N x 136, because there are 136 canonical 4-mers, instead of 256 total 4-mers.

The TNF of each sequence is calculated in the Cython file `src/_vambtools.pyx` by the function [`_fourmerfreq`](https://github.com/RasmussenLab/vamb/blob/858a3c153275c96c75f47875c709714859882f7d/src/_vambtools.pyx#L158). In this function, all 256 4-mers are first counted using the function [`c_kmercounts`](https://github.com/RasmussenLab/vamb/blob/858a3c153275c96c75f47875c709714859882f7d/src/_vambtools.pyx#L50), and this vector of counts is then converted to a vector of 136 canonical 4-mer frequencies using the function [`c_fourmer_freq`](https://github.com/RasmussenLab/vamb/blob/858a3c153275c96c75f47875c709714859882f7d/src/_vambtools.pyx#L113).

There is some precedent for using 4-mers in metagenomic binning ([Teeling et al. 2004](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1462-2920.2004.00624.x), [Kang et al. 2015](https://peerj.com/articles/1165/), [Pride et al. 2003](https://genome.cshlp.org/content/13/2/145), [Saeed et al. 2012](https://academic.oup.com/nar/article/40/5/e34/1101400)), however in tests, we have found 3-mers to have an almost-as-good signal as 4-mers. Since there are only 32 canonical 3-mers, fewer than 1/4 as many as there are 4-mers, it might make sense to use 3-mers in Vamb instead. We have not tested how well 3-mers work, but this could be an interesting avenue to pursue.

Closing this issue as resolved - you are welcome to reopen or open another issue if you have more questions

**Comment by apcamargo** [comment]
Thank you @jakobnissen!

I was studying Vamb's code and for some reason my local `_vambtools.pyx` file was truncated and I didn't see the `c_fourmer_freq` and `_fourmerfreq` functions.
