### ISSUE TITLE
vamb.vambtools.concatenate_fasta usage help

### ISSUE THREAD

**Issue by Lamm-a** [RasmussenLab/vamb#24]
I am trying to use `vamb.vambtools.concatenate_fasta` as you recommend in your workflow but I am struggling to locate any usage instructions for it and `help(vamb.vambtools.concatenate_fasta)` returns nothing for me either. Prehaps becuase I am using a conda install?

Cheers

**Comment by jakobnissen** [comment]
Dear @Lamm-a 
Yep, it's because you are using a conda install. I added `concatenate_fasta` to the v2.1.0 release, whereas the Conda install still uses v.2.0.1.
Problem is, I don't know how to update the Conda recipe, since it was originally added by another contributor. Although it is of course nice to have users be able to install Vamb using conda, I'm now stuck with the problem of having to keep Conda updated. I'll update the README.md.
Nothing *critical* have been changed since v2.0.1, so you can keep using that if you don't want to install using pip.

**Comment by Lamm-a** [comment]
I am able to instal via pip through conda but I get the following error:

`ERROR: Could not find a version that satisfies the requirement torch>=0.4 (from vamb==2.1.0) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=0.4 (from vamb==2.1.0)
`
Would for installing Pytorch fix this?

**Comment by jakobnissen** [comment]
Dear @Lamm-a 

This looks to be a problem with your Conda - it can't find the package `torch`. Yes, try manually installing PyTorch in your environment. Vamb should find it.

**Comment by jakobnissen** [comment]
@Lamm-a closing this issue as resolved - feel free to open another issue if you have more problems.
