### ISSUE TITLE
Use CoverM for coverage calculations

### ISSUE THREAD

**Issue by jakobnissen** [RasmussenLab/vamb#42]
Thanks to the suggestion of Antônio Pedro Camargo, use CoverM (or his Python wrapper, pycoverm) for coverage calculations. It's faster, more accurate, and simpler to use.

* Drop pysam dependency
* Fix dependencies in general (be stricter about versions)
* Review code to make sure Vamb is supported on Windows

**Comment by apcamargo** [comment]
Just to add a few things regarding pyCoverM:
- I'm already working on a function to check whether the BAM is sorted.
- I've never tried to build it on Windows. `rust-htslib` has some dependencies that may cause troubles, but I can work on that if you are considering to get Vamb to run on Windows.

**Comment by jakobnissen** [comment]
It's no great priority to be honest. I don't know anyone who runs bioinfo on a Windows computer. Of course it would be *nice* to have it run on all systems, but I'm not prepared to sacrifice anything for it. But thanks for the offer

**Comment by simonrasmu** [comment]
Current progress atm (branch v4):

- CoverM support is great - parsing of the BAM-files are very fast
- Vamb successfully runs, but exits with a segmentation error

**Comment by apcamargo** [comment]
Hi @simonrasmu!

I've been using pyCoverM heavily for around 8 months and I never got a segfault. Are you using a macOS build? I still need to implement a test CI to test them, as I don't use a Mac.

The fact that you're getting a segmentation fault indicates that the problem is an `unsafe` Rust block, which I don't use in pyCoverM's code. However it could come from other crates that I use. Do you got an reproducible example so I can try to figure out what's going on?

**Comment by simonrasmu** [comment]
Hi @apcamargo 

We are not sure yet whether the segfault is caused by CoverM or is something that happens from changing the code around it to make work with pyCoverM. It looks like the error could come from pytorch. Also it is using Linux so shouldn't be related to MacOS (haven't tested it yet though).

**Comment by jakobnissen** [comment]
Since I haven't seen any issues with pycoverm in ages, I'll go ahead and close this as completed.
