### ISSUE TITLE
Concatenate is just cat

### ISSUE THREAD

**Issue by SilasK** [RasmussenLab/vamb#43]
I hoped the concatenate.py does some complicated merging of assemblies. Anyway you might have heard of the dedupe.sh included in bbmap it merges small contigs into bigger ones and he's to de-duplicate or de-replicate assemblies.

**Comment by jakobnissen** [comment]
Dear @SilasK 

Thanks for showing an interest in Vamb. Yep, that behaviour is intentional. `cat` is short for "concatenate", you know. ;)

It's not *really* just `cat`, though. First, `concatenate.py` will rename your sequences to conform to the pattern required for the "multi-split" approach. Second, it won't mess up your FASTA file if some of them don't end with a trailing newline.

More importantly, you probably don't want to deduplicate assemblies - it doesn't really add anything useful. You probably want to run Vamb with  "binsplitting" enabled. By having more similar contigs of abundant organisms, this helps the cluster density of abundant genomes, making them easier to cluster out. They are then split by their sample to samplewise pure bins, such that you get the best of both worlds. You may then deduplicate the bins, if you wish.

Closing this issue, but you're welcome to re-open if you have more to add.
