### ISSUE TITLE
 Could not retrieve index file

### ISSUE THREAD

**Issue by xiaoluo91** [RasmussenLab/vamb#44]
Hi, I run vamb which was installed by pip, but got an error: Could not retrieve index file for 'sample1.bam',
please see the details as following:

$ vamb --outdir out --fasta contigs.fa --bamfiles sample1.bam -o C --minfasta 1

_[E::idx_find_and_load] Could not retrieve index file for 'sample1.bam'
Traceback (most recent call last):
  File "/software/miniconda3/envs/vamb/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/software/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/software/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 251, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/software/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 140, in trainvae
    destroy=True, cuda=cuda)
  File "/software/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/encode.py", line 74, in make_dataloader
    raise ValueError('Fewer sequences left after filtering than the batch size.')
ValueError: Fewer sequences left after filtering than the batch size._

So, I use samtools index to generate a index file for sample1.bam manually (samtools index sample1.bam), one need to 'samtool sort' before running samtools index, so I sorted the bam file and then index it, then run vamb. However, it reported another error like this:

  _File "/software/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/parsebam.py", line 229, in _check_bamfile
    raise ValueError(errormsg.format(path, sort_order))
ValueError: BAM file sample1.bam is marked with sort order 'coordinate', must be unsorted or sorted by readname._

Could you please give any advice to solve this problem? many thanks in advance.

**Comment by jakobnissen** [comment]
Dear @xiaoluo91

You're seeing three distinct errors:

* First, the output `[E::idx_find_and_load]`. This is a bug in one of the newer versions of `pysam`, one of the dependencies of Vamb. It basically searches for an index even though it doesn't need it. That'll be fixed by the `pysam` devs eventually. As far as I can tell it doesn't really do anything, so you can just ignore it.
* Second, the Vamb error `Fewer sequences left after filtering than the batch size`. What happens here is that too many of your sequences are being filtered away by the filters you have set when you run Vamb. So, for example, if you set `-m 10000`, but only have a few sequences longer than 10000, almost all data will be removed. Vamb also removes all sequences with a depth of zero in all samples, that is, sequences where exactly no reads mapped to it in any sample. To fix this, look at the logfile carefully and see how many sequences got filtered away. Also look at the BAM file - are there any mapped reads? Did you accidentally set any of the filtering parameters `-m`, `-s`, `-z` wrong?
* Last, the error `BAM file sample1.bam is marked with sort order 'coordinate', must be unsorted or sorted by readname` is straight forward: As stated in the README, to work with the current version of Vamb, all your BAM files must either be unsorted or sorted by read name. You can either just use the raw, unsorted BAM file, or sort it using `samtools sort -n`.

Let me know if that works out for you!

**Comment by xiaoluo91** [comment]
Many thanks for your detailed explanations. It helps a lot! Now I see the real problem is that I do not provide enough number of contigs(dozens of) so that the training process is failed. I changed the default batch size for training and problem solved.

**Comment by jakobnissen** [comment]
Hi @xiaoluo91. You probably don't want to use Vamb with just a few contigs. We don't know how many contigs you really need for Vamb to work well, but I would avoid Vamb if I had less than 10,000 contigs. We have only tested Vamb down to 50,000 contigs.

Closing the issue as the original problems are solved.

**Comment by xiaoluo91** [comment]
I see, thanks a lot.
