### ISSUE TITLE
Can Vamb bin Eukaryotes

### ISSUE THREAD

**Issue by SilasK** [RasmussenLab/vamb#49]
I don't know if you have thought about that question. Can I use to run VAMB to bin eukaryotes? Or another way around is there something that this should't work?

**Comment by SilasK** [comment]
Link: https://github.com/metagenome-atlas/atlas/issues/356

**Comment by jakobnissen** [comment]
Good question. We simply don't know. Give it a try!

On the surface, Vamb should be able to bin eukaryotes, since Vamb doesn't contain any bacteria-specific code. So it's a matter of whether the fundamental assumptions apply to eukaryotes:

* Can eukaryotes be assembled into decent contigs? Vamb needs both tens of thousands of contigs to not overfit, and also decently long contigs (> 2 kbp, longer is better). I think you can.
* Are eukaryote genomes distinguished effectively by tetranucleotide frequency (TNF)? Why not? A quick googling suggests it works fine for eukaryotes.
* Can you reliably estimate the abundance of eukaryotic contigs? This might be a bit more tricky, since eukaryotes are multiploid and plants undergo whole genome duplication. We also have more repetitive DNA. I would guess - and I dont know - that eukaryotes also have more frequent gene duplication. So this might be the tricky part - how to estimate the abundance of eukaryotic sequences. You might have to think carefully about how to construct your BAM files and how they should be filtered by Vamb.

Let us know what you find out - we're interested as well.

**Comment by jakobnissen** [comment]
Closing this issue as resolved.
