### ISSUE TITLE
Is co-assembly and subsequent diff binning possible?

### ISSUE THREAD

**Issue by openpaul** [RasmussenLab/vamb#56]
Hello,
VAMB is great. Thank you. 

I was wondering if VAMB could be used in a co-assembly setting. Sometimes co-assembly allows for recovery or more low abundance species. Currently I would assume for binning co-assembled contigs one would launch VAMB with the single assembly and merge all reads and provide them as a fake single sequencing run.

Would it be possible to pass many bam files and a single assembly to VAMB?

I understand that this is not the current aim (as seen in https://github.com/RasmussenLab/vamb/issues/52) but other binners allow this and it has some value.

**Comment by jakobnissen** [comment]
Hello, and thanks!

I don't know what you mean by "diff binning", but it's pretty easy to bin co-assembled contigs using Vamb. You don't need to do anything special - don't merge the reads, and you can still create one BAM file per sample. Just don't set the `-o` option (because binsplitting doesn't make sense with co-assembled reads).
