### ISSUE TITLE
Workflow output and resumption

### ISSUE THREAD

**Issue by andrewjmc** [RasmussenLab/vamb#70]
Being unfamiliar with snakemake (but having some experience with nextflow), it would be helpful to understand where output from each stage of the workflow is stored, and what persists or is deleted by the end (and any way of preserving intermediate files).

It would also be good to understand how to resume the pipeline, if interrupted, or rerun sections of the pipeline (for example if I wanted to rerun only the vamb step with different settings, but without redoing alignments).

Incidental question: what order of magnitude speedup should I expect with GPU acceleration?

Thanks!

Andrw

**Comment by andrewjmc** [comment]
And just to add to this, which file of the original output of vamb corresponds is the npz for the names parameter?

**Comment by simonrasmu** [comment]
Hi Andrew, 

Snakemake is able to resume any interrupted run you may have - just rerun snakemake in the same folder. The output from most of the steps should be relatively self-explanatory, ie:

rule cat_contigs: Concatenate contigs from different samples into a combined assembly, changing contig-names to SXCY where X is sample number and Y is contig number. This facilitates the multi-split approach greatly improving binning when having multiple samples. Furthermore it filters contigs smaller than 2000bp

rule index: Create Minimap2 index of the concatenated contig set.

rule dict: Create sequence dictionary of the concatenated contig set to facilitate efficient mapping

rule minimap: Maps reads from each sample to the concatenated contig set producing one bam-file per sample

rule sort: Sorts all bam-files by coordinate

rule jgi: Calculate jgi-abundance for each sorted bam-file in parallel

rule cut_column1to3: Extract the gene-names, lengths and total abundance from a single bam-file (total-abundance and length are not used, but included to conform to the jig-format)

rule cut_column4to5: For each bam-file extract abundance and variance determined by the jgi-script

rule paste_abundances: Combine the output from the cut_column* jobs so that it is a valid multi-sample jgi-abundance file

rule vamb: Run VAMB using the concatenated contig fasta and multi-sample jgi-abundance file

rule checkm: Run checkM on the resulting bins larger than specified in the configuration file

Best,

Simon

**Comment by andrewjmc** [comment]
Thanks. Is there any way just to rerun clustering when the model has already been generated? My run was interrupted.

**Comment by simonrasmu** [comment]
Sorry for the late reply - we do not have a script for just running the clustering, but one could write one up using the functions in the VAMB code. However, the easiest is to re-run from scratch (unless it is a very big dataset that takes a long time to encode).
