### ISSUE TITLE
Segmentation fault when using a high number of bam or large JGI depth file

### ISSUE THREAD

**Issue by bistace** [RasmussenLab/vamb#79]
Hello and thank you for developing Vamb, I find it very useful for my research.

We have sequenced a lot of marine samples and I would like to test Vamb for the binning step. However, the program crashes instantly with a segmentation fault, without any other error message, when all BAM files (aproximately 300 files) are given as input or when giving the corresponding depth file generated by jgi_summarize_depths. The error does not occur when giving the BAM files one by one.

Would it be possible that the large number of file causes a problem in the code or do you think that the problem is elsewhere (I have not tested all 300 BAM files one by one, I selected a few and it worked with a reduced number)?

**Comment by jakobnissen** [comment]
Given that the error is a segfault, the problem is almost certainly elsewhere. It's essentially impossible to segfault Python, which Vamb is written in. The exception would be the code in https://github.com/RasmussenLab/vamb/blob/master/src/_vambtools.pyx - but those are two relatively small functions. I'll just review them and their use anyway, just to be sure.

Anyway, the fact that it _instantly_ segfaults when using BAM or depths surprises me. When giving BAM files, Vamb ought to run parsebam.py first, and spend a lot of time parsing the BAM files. When passing the depth file, it should parse that instead, before encoding. If both instantly segfaults it implies to distinct code paths each segfault. Are you sure it's not in e.g encoding?

What does the logfile say? Does it segfault before it writes anything to the log?

**Comment by bistace** [comment]
It runs for about 5-6 seconds and then crashes with a segfault. There is nothing written in the log. I will contact the system administrators to see if there could be something with our install and will report back to you (can take a moment as it is holidays).

**Comment by jakobnissen** [comment]
If it really segfaults both with BAM and with depths within seconds, it's likely the segfault happens when Vamb imports its dependencies, or perhaps in some of the top-level calls in `vamb/__main.py__`, which call into these libraries. You can try running the top 32 lines of `vamb/__main.py__` in a script and see if it segfaults.

It's probably either Torch or Numpy. I've found lots of people, including myself, had had bad errors using PyTorch.

**Comment by bistace** [comment]
Just an update to tell you that running the first 32 lines of the `__main__.py` file didn't return an error.

**Comment by simonrasmu** [comment]
This is really strange - are you sure the BAM-files have the same header? Ie that they are mapped to the same contig set? 

What happens if you input two BAM-files instead of just one?

**Comment by simonrasmu** [comment]
Also, we have run VAMB on datasets of 2,000 samples without any problems so the 300 is definitely not something that should break it
