### ISSUE TITLE
How to write bins as fasta files?

### ISSUE THREAD

**Issue by tarunaaggarwal** [RasmussenLab/vamb#88]
Hello @jakobnissen - I'm having trouble writing the bin as fasta file and I'm hoping you can help me with getting the fasta bins. The tutorial.html in the `docs` folder is also not rendering as a regular webpage but is rather appearing as the raw code file. Please advise. Thank you!

**Comment by jakobnissen** [comment]
For the tutorial, you can download it and open it with a web browser.

To write the bins as FASTA, you can pass in e.g. `--minfasta 200000` to output all bins larger than 200000 bp. Be aware that there are a lot of small bins, so you likely want some kind of lower limit (i.e. you don't want to pass in `--minfasta 1`).

Closing this issue as solved, you're welcome to re-open it if you think otherwise.
