### ISSUE TITLE
Documentation page

### ISSUE THREAD

**Issue by vinisalazar** [RasmussenLab/vamb#89]
Hi,

Thank you for providing this tool, it is very useful.

Would you consider adding a documentation page (such as https://readthedocs.org/) for vamb? Like reported in #88, I was also initially confused on how to access the tutorial. A docs page could display the tutorial page and also an automatic API reference generated by Sphinx (with autodoc). If you agree, I'd be glad to help contributing to a Sphinx page for this project.

Thanks,
Vini

**Comment by jakobnissen** [comment]
Hey @vinisalazar 
Sorry for the delay in my response.

Vamb development is on the backburner for a while so I haven't had time to make a nice documentation page and such.
I'm a little worried about maintainability. No-one is really actively developing Vamb, and while that may change in the near future, I think it's better if for now, I strive to make Vamb as low-maintenance as possible. If the docs are built with some framework, it means I have to learn that framework to update the docs or fix it if it stops failing.

As an example of why that could be a problem, consider that I was hesitant to add Vamb to Conda in the beginning precisely because it would mean I'd have to maintain versions in both pip, conda and github. And now, because I forgot how to make pip/conda releases, users are reporting errors that has been fixed in the latest version.

So: Yes, a nice doc page is nice. But right now it is not a good idea to increase the maintenance burden of Vamb.

**Comment by vinisalazar** [comment]
Hi @jakobnissen,

thank you for the thoughtful reply. I completely understand that situation; the incentive structure in academia (unfortunately) does not allow for proper funding of research software and thus it almost always relies upon the core developer(s) to deliver these time-consuming tasks, and usually without much in return, other than the gratitude of their users.

What I'd like to say from my experience developing my own software packages, is that for both documentation and the other problem that you mentioned (distribution), it pays off in the long run to make the most out of these existing frameworks. While for docs I'd recommend readthedocs and Sphinx, in the case of distribution, what can be done is setting up GitHub Actions to automatically creating releases in Pip and Bioconda whenever you push a new tag. If your goal is to make maintenance easier, this would probably help. If you, or a contributor, would ever want any assistance with that, I'd be glad to try to help - Vamb is a promissing piece of software and it's proving to be very useful for my work.

Best wishes,
V
